- name: Replace clientID
  ansible.builtin.replace:
    path: /opt/SMAK/newnewWebinterface/appsettings.json
    regexp: '"ClientId": "",'
    replace: '{{ ClientId }}'

- name: Replace clientSecret
  ansible.builtin.replace:
    path: /opt/SMAK/newnewWebinterface/appsettings.json
    regexp: '"ClientSecret": ""'
    replace: '{{ ClientSecret }}'

- name: Copy webinterface service to host
  become: true
  become_user: root
  ansible.builtin.copy:
    src: ./templates/webinterface.service
    dest: "/etc/systemd/system/webinterface.service"
    mode: "0644"

- name: Enable webinterface service
  become: true
  become_user: root
  ansible.builtin.systemd_service:
    name: webinterface
    enabled: yes
    
- name: Start service webinterface
  ansible.builtin.systemd_service:
    name: webinterface
    daemon_reload: true
    state: restarted