- name: Ensure buildSH is executable
  ansible.builtin.file:
    path: "{{ app3_dir }}/build.sh"
    mode: "0755"

- name: Replace http://localhost:9090 with correct hostname
  ansible.builtin.replace:
    path: /opt/SMAK/webinterface/geteval.ts
    regexp: 'http://localhost:9090'
    replace: 'https://smakanalysis.head9x.dk'

- name: Run buildSH
  ansible.builtin.command: ./build.sh
  args:
    chdir: "{{ app3_dir }}"
  register: build_result
  failed_when: >
    build_result.rc != 0 and
    "'tsc' not in build_result.stderr"

- name: Copy smak webinterface to varwwwhtml
  become: true
  become_user: root
  ansible.builtin.copy:
    src: "{{ app3_dir }}"
    dest: "/var/www/html/"
    mode: "0777"
    remote_src: true
