/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/smak.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SMAK_CHESS_MOVE, smak_chess_move_t, AUTO)


PB_BIND(BOARD_MOVE, board_move_t, AUTO)


PB_BIND(SMAK_NEW_GAME, smak_new_game_t, AUTO)


PB_BIND(SMAK_MESSAGE, smak_message_t, AUTO)





