/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/smak.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Smak_ChessMove, Smak_ChessMove, AUTO)


PB_BIND(BoardMove, BoardMove, AUTO)



