caddy_email: "admin@example.com"

caddy_sites:
  #- name: "webinterface.head9x.dk"
  #  listen: "http://webinterface.head9x.dk"
  #  root: "/var/www/html/webinterface"
  #  file_server: true

  - name: "smak.head9x.dk"
    listen: "http://smak.head9x.dk"
    reverse_proxy: "127.0.0.1:5022"
    proxy_headers:
      - "X-Forwarded-Host {host}"
      - "X-Forwarded-Proto https"
    extra_headers:
      - "X-Content-Type-Options nosniff"
      - "X-Frame-Options DENY"

  - name: "smakanalysis.head9x.dk"
    listen: "http://smakanalysis.head9x.dk"
    reverse_proxy: "127.0.0.1:9090"

  - name: "smakdb.head9x.dk"
    listen: "http://smakdb.head9x.dk"
    reverse_proxy: "127.0.0.1:8080"
    proxy_headers:
      - "Host smakanalysis.head9x.dk"
      - "X-Forwarded-Host {host}"