caddy_email: "admin@example.com"

caddy_sites:
  #- name: "webinterface.appserver.dk"
  #  listen: "http://webinterface.appserver.dk"
  #  root: "/var/www/html/webinterface"
  #  file_server: true

  - name: "webinterface.appserver.dk"
    listen: "http://webinterface.appserver.dk"
    reverse_proxy: "127.0.0.1:5200"

  - name: "smakanalysis.appserver.dk"
    listen: "http://smakanalysis.appserver.dk"
    reverse_proxy: "127.0.0.1:9090"

  - name: "smakdb.appserver.dk"
    listen: "http://smakdb.appserver.dk"
    reverse_proxy: "127.0.0.1:8080"
    proxy_headers:
      - "Host smakanalysis.appserver.dk"
      - "X-Forwarded-Host {host}"